apiVersion: redisoperator.nevercase.io/v1
kind: RedisOperator
metadata:
  name: example-redis
spec:
  master_spec:
    deploymentName: "test-redis-operator"
    replicas: 1
    image: redis:latest
    imagePullSecrets: ""
  slave_spec:
    deploymentName: "test-redis-operator"
    replicas: 4
    image: domain.com/redis-slave:1.0
    imagePullSecrets: self-secret