apiVersion: redisoperator.nevercase.io/v1
kind: RedisOperator
metadata:
  name: example-redis
spec:
  masterSpec:
    spec:
      name: "redis-cn1"
      replicas: 1
      image: harbor.domain.com/helix-saga/redis-slave:1.1
      imagePullSecrets:
        - name: private-harbor
      volumePath: /mnt/nas1
      containerPorts:
        - containerPort: 6379
          protocol: TCP
      servicePorts:
        - port: 6379
          protocol: TCP
          targetPort: 6379
      resources:
        limits:
          memory: "1Gi"
          cpu: "100m"
        requests:
          memory: "0.5Gi"
          cpu: "100m"
  slaveSpec:
    spec:
      name: "redis-cn1"
      replicas: 4
      image: harbor.domain.com/helix-saga/redis-slave:1.1
      imagePullSecrets:
        - name: private-harbor
      volumePath: /mnt/nas1
      containerPorts:
        - containerPort: 6379
          protocol: TCP
      servicePorts:
        - port: 6379
          protocol: TCP
          targetPort: 6379
      resources:
        limits:
          memory: "1Gi"
          cpu: "100m"
        requests:
          memory: "0.5Gi"
          cpu: "100m"