/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/nevercase/k8s-controller-custom-resource/api/proto/generated.proto

package proto

import (
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_b20386f0595f5278, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetService() string {
	if m != nil && m.Service != nil {
		return *m.Service
	}
	return ""
}

func (m *Request) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_b20386f0595f5278, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int64 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *Response) GetResult() string {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "github.com.nevercase.k8s_controller_custom_resource.api.proto.Request")
	proto.RegisterType((*Response)(nil), "github.com.nevercase.k8s_controller_custom_resource.api.proto.Response")
}

func init() {
	proto.RegisterFile("github.com/nevercase/k8s-controller-custom-resource/api/proto/generated.proto", fileDescriptor_b20386f0595f5278)
}

var fileDescriptor_b20386f0595f5278 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8d, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0x47, 0x55, 0xfe, 0x05, 0x3c, 0x7a, 0x40, 0x19, 0x51, 0x27, 0x96, 0xd8, 0x1b, 0x74, 0x61,
	0x61, 0x67, 0xf1, 0xc8, 0x12, 0x19, 0xe7, 0x54, 0xac, 0x26, 0x3e, 0x73, 0x77, 0xce, 0xe7, 0x47,
	0x72, 0x92, 0x66, 0xfb, 0x3d, 0x5b, 0xef, 0x9d, 0xfa, 0x3a, 0x47, 0xf9, 0x2d, 0x3f, 0x26, 0xe0,
	0x64, 0x13, 0xcc, 0x40, 0xc1, 0x33, 0xd8, 0xcb, 0x89, 0xbb, 0x80, 0x49, 0x08, 0xc7, 0x11, 0xa8,
	0x0b, 0x85, 0x05, 0xa7, 0x8e, 0x80, 0xb1, 0x50, 0x00, 0xeb, 0x73, 0xb4, 0x99, 0x50, 0xd0, 0x9e,
	0x21, 0x01, 0x79, 0x81, 0xc1, 0x54, 0xd6, 0x1f, 0x7b, 0xce, 0x5c, 0x73, 0xe6, 0x72, 0xe2, 0x7e,
	0xcf, 0xf5, 0x4b, 0xae, 0xdf, 0x72, 0xc6, 0xe7, 0xb8, 0xe8, 0xc7, 0x77, 0xd5, 0x38, 0xf8, 0x2b,
	0xc0, 0xa2, 0x5b, 0xd5, 0x30, 0xd0, 0x1c, 0x03, 0xb4, 0x87, 0x97, 0xc3, 0xeb, 0x93, 0xdb, 0x50,
	0x6b, 0x75, 0x37, 0x78, 0xf1, 0xed, 0x4d, 0x7d, 0xae, 0xfb, 0xf8, 0xa6, 0x1e, 0x1d, 0x70, 0xc6,
	0xc4, 0xf5, 0x3f, 0xe0, 0xb0, 0x68, 0xb7, 0xae, 0x6e, 0xfd, 0xac, 0x1e, 0x08, 0xb8, 0x8c, 0xb2,
	0x5a, 0x2b, 0x7d, 0x36, 0xdf, 0xf7, 0xf5, 0xf2, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x43, 0x0a,
	0x92, 0x92, 0x08, 0x01, 0x00, 0x00,
}
