/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!


goog.provide('proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request');
goog.provide('proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request.displayName = 'proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request.prototype.toObject = function(opt_includeInstance) {
  return proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request.toObject = function(includeInstance, msg) {
  var f, obj = {
    service: jspb.Message.getField(msg, 1),
    data: jspb.Message.getField(msg, 2)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request}
 */
proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request;
  return proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request}
 */
proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setService(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string service = 1;
 * @return {string}
 */
proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request.prototype.getService = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request.prototype.setService = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request.prototype.clearService = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request.prototype.hasService = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string data = 2;
 * @return {string}
 */
proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request.prototype.getData = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request.prototype.setData = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request.prototype.clearData = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Request.prototype.hasData = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response.displayName = 'proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response.prototype.toObject = function(opt_includeInstance) {
  return proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response.toObject = function(includeInstance, msg) {
  var f, obj = {
    code: jspb.Message.getField(msg, 1),
    result: jspb.Message.getField(msg, 2)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response}
 */
proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response;
  return proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response}
 */
proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setResult(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional int64 code = 1;
 * @return {number}
 */
proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response.prototype.getCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response.prototype.setCode = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response.prototype.clearCode = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response.prototype.hasCode = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string result = 2;
 * @return {string}
 */
proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response.prototype.getResult = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response.prototype.setResult = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response.prototype.clearResult = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.github.com.nevercase.k8s_controller_custom_resource.api.proto.Response.prototype.hasResult = function() {
  return jspb.Message.getField(this, 2) != null;
};


