apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-multiplex-crd
  namespace: kube-api
  labels:
    app: k8s-multiplex-crd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-multiplex-crd
  template:
    metadata:
      labels:
        app: k8s-multiplex-crd
    spec:
      serviceAccountName: k8s-api-controller
      containers:
        - name: k8s-multiplex-crd
          image: harbor.domain.com/lunara-common/multiplex-crd:v1.0.0
          imagePullPolicy: Always
          command: ["/data/multiplex-crd"]
          args:
            - -alsologtostderr=true
            - -v
            - "4"
      imagePullSecrets:
        - name: harbor-secret