apiVersion: mysqloperator.nevercase.io/v1
kind: MysqlOperator
metadata:
  name: example-mysql
spec:
  masterSpec:
    spec:
      name: "mysql-cn1"
      replicas: 1
      image: 39.99.229.222:37229/helix-saga/mysql-slave:1.0
      imagePullSecrets:
        - name: private-harbor
  slaveSpec:
    spec:
      name: "mysql-cn1"
      replicas: 4
      image: 39.99.229.222:37229/helix-saga/mysql-slave:1.0
      imagePullSecrets:
        - name: private-harbor