apiVersion: mysqloperator.nevercase.io/v1
kind: MysqlOperator
metadata:
  name: example-mysql
spec:
  masterSpec:
    spec:
      name: "mysql-cn1"
      replicas: 1
      image: harbor.domain.com/helix-saga/mysql-slave:1.0
      imagePullSecrets:
        - name: private-harbor
      volumePath: /mnt/nas1
      containerPorts:
        - containerPort: 3306
          protocol: TCP
      servicePorts:
        - port: 3306
          protocol: TCP
          targetPort: 3306
      resources:
        limits:
          memory: "1Gi"
          cpu: "100m"
        requests:
          memory: "0.5Gi"
          cpu: "100m"
  slaveSpec:
    spec:
      name: "mysql-cn1"
      replicas: 4
      image: harbor.domain.com/helix-saga/mysql-slave:1.0
      imagePullSecrets:
        - name: private-harbor
      volumePath: /mnt/nas1
      containerPorts:
        - containerPort: 3306
          protocol: TCP
      servicePorts:
        - port: 3306
          protocol: TCP
          targetPort: 3306
      resources:
        limits:
          memory: "1Gi"
          cpu: "100m"
        requests:
          memory: "0.5Gi"
          cpu: "100m"