apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqloperators.nevercase.io
spec:
  group: nevercase.io
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: MysqlOperator
    plural: mysqloperators
    singular: mysqloperator
    shortNames:
      - mo
  scope: Namespaced