apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqloperators.nevercase.io
spec:
  group: nevercase.io
  version: v1
  names:
    kind: MysqlOperator
    plural: mysqloperators
  scope: Namespaced