apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-api-server
  namespace: kube-api
  labels:
    app: k8s-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-api-server
  template:
    metadata:
      labels:
        app: k8s-api-server
    spec:
      serviceAccountName: k8s-api-controller
      containers:
        - name: k8s-api
          image: harbor.domain.com/lunara-common/api-server:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          command: ["/data/api-server"]
          args:
            - -alsologtostderr=true
            - --apiservice=0.0.0.0:9090
            - -v
            - "4"
            - -dockerurl=http://harbor.domain.com
            - -dockeradmin=admin
            - -dockerpwd=password
      imagePullSecrets:
        - name: harbor-secret
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-api-server
  namespace: kube-api
  labels:
    app: k8s-api-server
spec:
  selector:
    app: k8s-api-server
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9090