kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8s-api-controller
  namespace: kube-api
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - services
      - endpoints
      - secrets
      - namespaces
      - configmaps
      - pods
      - pods/log
      - pods/exec
      - nodes
      - persistentvolumes
      - persistentvolumeclaims
      - serviceaccounts
    verbs:
      - create
      - get
      - list
      - watch
      - delete
      - update
      - patch
  - apiGroups:
      - "apps"
    resources:
      - statefulsets
      - deployments
    verbs:
      - create
      - get
      - list
      - watch
      - delete
      - update
      - patch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - create
      - get
      - list
      - watch
      - delete
      - update
      - patch
  - apiGroups:
      - nevercase.io
    resources:
      - mysqloperators
      - redisoperators
      - helixsagas
    verbs:
      - create
      - get
      - list
      - watch
      - delete
      - update
      - patch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8s-api-controller
  namespace: kube-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-api-controller
subjects:
  - kind: ServiceAccount
    name: k8s-api-controller
    namespace: kube-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-api-controller
  namespace: kube-api
secrets: